import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Bird,LayoutDashboard,Radio,ListTodo,Activity,ArrowUpRight,RefreshCw,ChevronRight,AlertCircle,Check,LogOut,CloudSun,Feather,WifiOff} from 'lucide-react';
import './style.css';
import {ForecastComparison, type QuestionDetail} from './ForecastComparison';

type Event = {id:string;source:string;at:string;title:string;detail:string;url?:string;origin:string};
type RecordRow=QuestionDetail & {id:string;question_id:number;type:string;status:string;resolution:string;outcome?:string|null;scores:{metric:string;value:number;version:string}[];at:string;url?:string;uncertainties:number};
type Task={id:string;title:string;project:string;due:string|null;parent:string|null;url?:string};
type Metrics={pnl:string|null;open_stake:string|null;open_count:number;settled_count:number;settled_stake:string|null};
type Observation={health_notes?:string[];origin:'real'|'demo';source_observed_at:string|null;heartbeat_at:string|null;heartbeat_note?:string|null;job_success_at:string|null;coverage:string;provenance:string;data:{scopes?:{[key:string]:Metrics};current_epoch?:string;bankroll?:string;records?:RecordRow[];actual?:string;reserved?:string;tasks?:Task[]}};
type Source={id:string;connection:string;collected_at:string|null;attempt_at:string|null;error:string|null;cache_stale:boolean;observation:Observation|null};
type Incident={id:string;source:string;title:string;acknowledged_at:string|null;recovered_at:string|null};
type Dashboard={sources:Source[];events:Event[];incidents:Incident[];worker:{alive:boolean;heartbeat:string|null};outbox:{id:string;status:string}[]};
const names:{[key:string]:string}={wethr:'WETHR',whiskeyjack:'Whiskey Jack',quire:'Quire'};
const tabs=[{id:'overview',name:'Overview',icon:LayoutDashboard},{id:'bots',name:'Bots',icon:Radio},{id:'tasks',name:'Tasks',icon:ListTodo},{id:'activity',name:'Activity',icon:Activity}];
const date=(s:string|null|undefined)=>s?new Intl.DateTimeFormat('en-CA',{timeZone:'America/Edmonton',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(s)):'Unknown';
const money=(v:string|null|undefined)=>v==null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v));
const safe=(u:string|undefined)=>{try{const x=new URL(u||'');return x.protocol==='https:'?x.href:undefined}catch{return undefined}};
function App(){
 const [csrf,setCsrf]=useState(''),[authenticated,setAuthenticated]=useState(false),[password,setPassword]=useState(''),[data,setData]=useState<Dashboard|null>(null),[tab,setTab]=useState(location.hash.slice(1)||'overview'),[epoch,setEpoch]=useState('current'),[offline,setOffline]=useState(!navigator.onLine),[message,setMessage]=useState(''),[filter,setFilter]=useState('all'),[project,setProject]=useState('all');
 const api=async(path:string,method='GET',body?:unknown)=>{const res=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});if(!res.ok){if(res.status===401){setAuthenticated(false);setData(null)}throw new Error(res.status===401?(path==='login'?'Incorrect password. Check PASSERINE_PASSWORD in .env and restart the server after changing it.':'Sign in to your private observatory'):res.status===403?'This browser address is not authorized. Open the address configured in PASSERINE_ORIGIN.':`Request failed (${res.status})`)}return res.json()};
 const load=async()=>{try{const d=await api('overview');setData(d);setOffline(false)}catch(e){if(e instanceof TypeError)setOffline(true)}};
 useEffect(()=>{fetch('/api/session').then(async r=>{if(r.ok){setCsrf((await r.json()).csrf);setAuthenticated(true)}}).catch(()=>setOffline(true));const change=()=>setTab(location.hash.slice(1)||'overview');const off=()=>setOffline(true);window.addEventListener('hashchange',change);window.addEventListener('offline',off);return()=>{window.removeEventListener('hashchange',change);window.removeEventListener('offline',off)}},[]);
 useEffect(()=>{if(authenticated){load();const id=setInterval(load,20000);return()=>clearInterval(id)}},[authenticated]);
 const navigate=(id:string)=>{location.hash=id;setTab(id);setMessage('')};
 const login=async(e:React.FormEvent)=>{e.preventDefault();try{const result=await api('login','POST',{password});setCsrf(result.csrf);setAuthenticated(true);setPassword('');setMessage('')}catch(e){setMessage(e instanceof TypeError?'Cannot reach the Passerine server. Start scripts/run-local.sh on the host, then reload this page.':e instanceof Error?e.message:'Login failed. Please try again.')}};
 const logout=async()=>{try{await api('logout','POST');setAuthenticated(false);setData(null);setCsrf('')}catch{setMessage('Could not sign out. Reconnect and try again.')}};
 const sources=data?.sources||[];
 const source=(id:string)=>sources.find(s=>s.id===id);
 const w=source('wethr'),j=source('whiskeyjack'),q=source('quire');
 const active=data?.incidents.filter(i=>!i.recovered_at)||[];
 const scope=epoch==='current'?w?.observation?.data.current_epoch:epoch;
 const metrics=w?.observation?.data.scopes?.[scope||'all'];
 const demo=sources.some(s=>s.observation?.origin==='demo');
 const badge=(s:Source|undefined)=><span className={'badge '+(s?.error?'warn':'')}>{s?.observation?.origin==='demo'?'DEMO':s?.error?'Attention':s?.connection==='connected'?'Connected':'Not configured'}</span>;
 const freshness=(s:Source|undefined)=><div className="evidence"><span>Monitor contact <b>{date(s?.attempt_at)}</b></span><span>Last successful read <b>{date(s?.collected_at)}</b></span><span>Latest recorded event <b>{date(s?.observation?.source_observed_at)}</b></span><span>{s?.id==='whiskeyjack'?'Recorded tournament heartbeat':'Bot heartbeat'} <b>{date(s?.observation?.heartbeat_at)}</b></span><span>Successful job <b>{date(s?.observation?.job_success_at)}</b></span>{s?.observation?.heartbeat_note&&<p>{s.observation.heartbeat_note}</p>}{(s?.cache_stale||s?.error)&&<p className="warning">{s?.error||'Cached observation is stale; collection has not advanced.'}</p>}<p>Ledger activity and a recent read do not establish bot health.</p></div>;
 const events=(items:Event[])=><div className="event-list">{items.length?items.map(e=><article className="event" key={e.id}><span className="event-dot"/><div><small>{names[e.source]} · {date(e.at)} {e.origin==='demo'?'· DEMO':''}</small><h3>{e.title}</h3><p>{e.detail}</p>{safe(e.url)&&<a href={safe(e.url)} target="_blank" rel="noreferrer">Open source <ArrowUpRight size={13}/></a>}</div></article>):<p className="empty">No recorded activity yet. The worker collects independently of this screen.</p>}</div>;
 const botCards=()=> <div className="bot-grid"><button className="bot-card" onClick={()=>navigate('wethr')}><div className="card-top"><span className="source-icon"><CloudSun/></span>{badge(w)}</div><p className="eyebrow">WEATHER RESEARCH</p><h2>WETHR <ChevronRight size={20}/></h2><div className="big-number">{money(w?.observation?.data.scopes?.[w.observation.data.current_epoch||'']?.pnl)}</div><p>Gross realized paper P&L · current epoch</p><div className="card-bottom"><span>USD · fees excluded</span><span>Bot health unknown</span></div></button><button className="bot-card" onClick={()=>navigate('whiskeyjack')}><div className="card-top"><span className="source-icon blue"><Feather/></span>{badge(j)}</div><p className="eyebrow">MINIBENCH FORECASTING</p><h2>Whiskey Jack <ChevronRight size={20}/></h2><div className="big-number">{j?.observation?.data.records?.length??'—'} <span>forecasts recorded</span></div><p>{j?.observation?.data.records?.filter(r=>r.resolution==='resolved').length??'—'} with resolved evidence · local diagnostics</p><div className="card-bottom"><span>Resolution checks every 6h</span><span>Bot health unknown</span></div></button></div>;
 if(!authenticated)return <main className="login"><div className="brand"><Bird size={32}/> passerine<span>PRIVATE OBSERVATORY</span></div><form onSubmit={login}><p className="eyebrow">A LITTLE LESS CHECKING</p><h1>Your systems.<br/>One quiet place.</h1><p>Sign in to see the latest field notes from your bots and tasks.</p><label htmlFor="password">Private access password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="primary">Open Passerine <ArrowUpRight size={18}/></button><p role="status">{offline?'Offline · reconnect to your private server':message}</p></form><small>WETHR / WHISKEY JACK / QUIRE</small></main>;
 return <div className="app"><aside><a className="brand" href="#overview"><Bird size={30}/> passerine<span>PRIVATE OBSERVATORY</span></a><div className="workspace-label">YOUR WORKSPACE</div><nav>{tabs.map(t=><button key={t.id} className={(tab===t.id||(t.id==='bots'&&['wethr','whiskeyjack'].includes(tab)))?'selected':''} onClick={()=>navigate(t.id)}><t.icon size={19}/><span>{t.name}</span>{t.id==='activity'&&active.length>0&&<i>{active.length}</i>}</button>)}</nav><div className="sidebar-foot"><span className="pulse"/> Personal workspace<p>America / Edmonton</p><button onClick={logout}><LogOut size={15}/> Sign out</button></div></aside><div className="page"><header><span><span className="header-dot"/> Chris’s field notes</span><span>PRIVATE · READ ONLY <button className="header-logout" aria-label="Sign out" onClick={logout}><LogOut size={15}/></button></span></header><main><div className="title-row"><div><p className="eyebrow">{new Intl.DateTimeFormat('en-CA',{timeZone:'America/Edmonton',weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p><h1>{({overview:'A view from the perch.',bots:'Your working flock.',tasks:'Room for the next thing.',activity:'The latest field notes.',wethr:'WETHR',whiskeyjack:'Whiskey Jack'} as {[key:string]:string})[tab]||'Passerine'}</h1><p>{tab==='overview'?'What changed, what needs attention, and what we know.':tab==='tasks'?'Quire stays the source of truth.':'Recorded evidence, with its limits in view.'}</p></div><button className="refresh" onClick={async()=>{try{const r=await api('refresh','POST');await load();setMessage(r.message)}catch{setMessage('Refresh unavailable')}}}><RefreshCw size={16}/><span>Refresh view</span></button></div>{message&&<p className="notice" role="status">{message}</p>}{offline&&<div className="notice warning" role="alert"><WifiOff size={18}/> Offline · displayed observations are not current.</div>}{demo&&<div className="notice">Demo workspace · synthetic scenarios fixed at September 18, 2026. No production health claims.</div>}{data&&!data.worker.alive&&<div className="notice warning" role="alert">Polling worker unavailable or stale · last heartbeat {date(data.worker.heartbeat)}</div>}
 {(tab==='overview'||tab==='bots')&&<><div className="section-title"><h2>Your bots</h2><span>02 SOURCES</span></div>{botCards()}</>}
 {tab==='overview'&&<><div className="overview-grid"><section className="panel attention"><div className="section-title"><h2><AlertCircle size={18}/> Needs a look</h2><span>{active.length} OPEN</span></div>{active.length?active.map(i=><div className="incident" key={i.id}><span className="amber-dot"/><div><small>{names[i.source]}</small><h3>{i.title}</h3><p>{i.acknowledged_at?'Acknowledged · condition remains open':'Cached data is retained when a source fails.'}</p><button className="text-button" disabled={!!i.acknowledged_at} onClick={async()=>{try{await api('ack/'+encodeURIComponent(i.id),'POST');await load()}catch{setMessage('Acknowledgement failed')}}}>{i.acknowledged_at?<><Check size={14}/> Acknowledged</>:'Acknowledge'}</button></div></div>):<div className="empty"><Check/><p>No source connection incidents.</p><small>Missing heartbeat and job evidence remain unknown.</small></div>}{sources.flatMap(s=>(s.observation?.health_notes||[]).map((note,i)=><div className="incident" key={s.id+i}><AlertCircle size={16}/><div><small>{names[s.id]} · DEMO SCENARIO</small><p>{note}</p></div></div>))}<div className="quiet-note">Acknowledging an incident does not clear the condition.</div></section><section className="panel"><div className="section-title"><h2>Coming up</h2><ListTodo size={18}/></div>{q?.observation?.data.tasks?.slice(0,3).map(t=><div className="task" key={t.id}><span className="checkbox"/><div><h3>{t.title}</h3><small>{t.project} · {t.due||'No due date'} · DEMO</small></div></div>)||<div className="empty"><ListTodo size={30}/><h3>Connect your task world</h3><p>Quire is disconnected. Tasks will appear after a complete, authorized sync.</p></div>}<button className="text-button" onClick={()=>navigate('tasks')}>View tasks <ArrowUpRight size={14}/></button></section></div><section className="panel"><div className="section-title"><h2>Recent activity</h2><button className="text-button" onClick={()=>navigate('activity')}>All field notes <ArrowUpRight size={14}/></button></div>{events((data?.events||[]).slice(0,5))}</section></>}
 {tab==='wethr'&&<><div className="section-title"><h2>Paper ledger {badge(w)}</h2><label>Scope <select value={epoch} onChange={e=>setEpoch(e.target.value)}><option value="current">Current epoch</option><option value="all">All recorded history</option>{Object.keys(w?.observation?.data.scopes||{}).filter(x=>x!=='all').map(x=><option key={x}>{x}</option>)}</select></label></div><div className="metrics"><div><small>Gross realized paper P&L · USD</small><strong>{money(metrics?.pnl)}</strong><p>{metrics?.settled_count??'—'} settled records</p></div><div><small>Current epoch bankroll · USD</small><strong>{money(w?.observation?.data.bankroll)}</strong><p>{w?.observation?.data.current_epoch} · independent of filter</p></div><div><small>Open paper stake · USD</small><strong>{money(metrics?.open_stake)}</strong><p>{metrics?.open_count??'—'} unsettled records</p></div></div><section className="panel"><h2>Evidence & coverage</h2><p>{w?.observation?.coverage}</p><p>Paper accounting only. Fees, net, live and unrealized P&L unavailable.</p>{freshness(w)}</section><section className="panel"><h2>Recent settlements · all epochs</h2>{events((data?.events||[]).filter(e=>e.source==='wethr').slice(0,25))}</section></>}
 {tab==='whiskeyjack'&&<><div className="section-title"><h2>MiniBench {badge(j)}</h2><span>LOCAL DIAGNOSTICS</span></div><div className="metrics"><div><small>Recorded forecasts</small><strong>{j?.observation?.data.records?.length??'—'}</strong><p>Generation is not proof of submission</p></div><div><small>Settled actual cost · USD</small><strong>{money(j?.observation?.data.actual)}</strong><p>Latest activation scope</p></div><div><small>Unsettled reserved estimates · USD</small><strong>{money(j?.observation?.data.reserved)}</strong><p>Excludes settled reservations</p></div></div><section className="panel"><h2>Questions & forecasts</h2><p>Latest resolution evidence overrides historical lifecycle status. Official platform scores are unavailable.</p><div className="records">{j?.observation?.data.records?.slice().sort((a,b)=>b.at.localeCompare(a.at)).map(r=><article key={r.id}><div><small>{r.type} · {date(r.at)}</small><small>Question {r.question_id}</small>{r.group_title&&<p className="group-question">{r.group_title}</p>}<h3>{r.title||`Question ${r.question_id}`}</h3><p>Lifecycle: {r.status} · uncertainties: {r.uncertainties}</p>{safe(r.url)&&<a href={safe(r.url)} rel="noreferrer" target="_blank">Open on Metaculus <ArrowUpRight size={13}/></a>}</div><div><span className="badge">{r.resolution}{r.outcome?` · ${r.outcome}`:''}</span><p>{r.scores.length?r.scores.map(s=>`${s.metric}: ${s.value.toFixed(4)} (${s.version})`).join(' · '):r.type==='numeric'||r.type==='discrete'?'Local scoring out of scope':r.resolution==='resolved'?'Awaiting local score':'No current eligible score'}</p></div><ForecastComparison record={r} date={date}/></article>)}</div></section><section className="panel"><h2>Source health</h2><p>{j?.observation?.coverage}</p><p>Cup is intentionally dormant; it receives no downtime alert. Refreshing this view does not trigger resolution ingestion or scoring.</p>{freshness(j)}</section></>}
 {tab==='tasks'&&<section className="panel"><div className="section-title"><h2>Quire {badge(q)}</h2><label>Project <select value={project} onChange={e=>setProject(e.target.value)}><option value="all">All projects</option>{[...new Set(q?.observation?.data.tasks?.map(t=>t.project)||[])].map(p=><option key={p}>{p}</option>)}</select></label></div>{q?.observation?.data.tasks?.filter(t=>project==='all'||t.project===project).map(t=><div className="task" key={t.id}><span className="checkbox"/><div>{t.parent&&<small>↳ {t.parent}</small>}<h3>{t.title}</h3><p>{t.project} · Due {t.due||'unscheduled'} · date preserved as entered</p>{safe(t.url)&&<a href={safe(t.url)}>Open in Quire</a>}</div></div>)||<div className="empty large"><ListTodo size={44}/><h2>A place for what’s next.</h2><p>Quire isn’t connected yet. No task data has been imported.</p><p>Required: a registered read-access OAuth app, selected project IDs, and a verified task reader with complete child traversal. See the setup guide.</p></div>}</section>}
 {tab==='activity'&&<section className="panel"><div className="section-title"><h2>Recorded activity</h2><label>Source <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All sources</option>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>{events((data?.events||[]).filter(e=>filter==='all'||e.source===filter))}<p className="quiet-note">Latest 150 events. Notification delivery disabled; {data?.outbox.length||0} durable intents retained. Existing bot notifications remain in place.</p></section>}
 <footer><Bird size={16}/><span>Passerine · a quieter view of your systems</span><span>Monitor {data?.worker.alive?'running':'unknown'} · Edmonton time</span></footer></main></div></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
if('serviceWorker' in navigator && import.meta.env.PROD) navigator.serviceWorker.register('/sw.js');
